apiVersion: com.datastax.oss/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
spec:
  global:
    name: pulsar
    image: datastax/lunastreaming-core:2.10_2.3
    storage:
      existingStorageClassName: default
  zookeeper:
    replicas: 3
  bookkeeper:
    replicas: 3
  broker:
    replicas: 3
    autoscaler:
      enabled: false
      periodMs: 20000
      min: 3
      max: 10
      lowerCpuThreshold: 0.1
      higherCpuThreshold: 0.4
      scaleUpBy: 1
      scaleDownBy: 1
      stabilizationWindowMs: 300000
  proxy:
    replicas: 1
