apiVersion: com.datastax.oss/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
spec:
  global:
    name: pulsar
    fullname: pulsar
    restartOnConfigMapChange: false
    enableTls: false
    persistence: true
  zookeeper:
    component: zookeeper
    replicas: 1
    config:
      PULSAR_MEM: "-Xms1g -Xmx1g -Dcom.sun.management.jmxremote -Djute.maxbuffer=10485760"
      PULSAR_GC: "-XX:+UseG1GC"
      PULSAR_LOG_LEVEL: "info"
      PULSAR_LOG_ROOT_LEVEL: "info"
      PULSAR_EXTRA_OPTS: "-Dzookeeper.tcpKeepAlive=true -Dzookeeper.clientTcpKeepAlive=true -Dpulsar.log.root.level=info"
    podManagementPolicy: Parallel
    containerImage: datastax/lunastreaming-core:2.10_2.3
    imagePullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
    probe:
      enabled: true
      initial: 20
      period: 30
      timeout: 30
    gracePeriod: 60
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
    dataVolume:
      name: data
      size: 5Gi
      # K3S storage class name https://docs.k3s.io/storage
      existingStorageClassName:  local-path
    service:
      ports:
        - name: server
          port: 2888
        - name: leader-election
          port: 3888
        - name: client
          port: 2181




