apiVersion: com.datastax.oss/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
spec:
  global:
    name: pulsar
    image: datastax/lunastreaming-core:2.10_2.3
    persistence: true
  zookeeper:
    replicas: 1
    config:
      PULSAR_MEM: "-Xms1g -Xmx1g -Dcom.sun.management.jmxremote -Djute.maxbuffer=10485760"
      PULSAR_GC: "-XX:+UseG1GC"
      PULSAR_LOG_LEVEL: "info"
      PULSAR_LOG_ROOT_LEVEL: "info"
      PULSAR_EXTRA_OPTS: "-Dzookeeper.tcpKeepAlive=true -Dzookeeper.clientTcpKeepAlive=true -Dpulsar.log.root.level=info"
    dataVolume:
      name: data
      size: 100M
      # K3S storage class name https://docs.k3s.io/storage
      existingStorageClassName:  local-path



