---
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: pulsar-operator

## Whether to create the CRD.
crd:
  create: true


operator:
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/live
  image: nicoloboschi/pulsar-operator:latest
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/ready