{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulsaroperatorapp-crd-validating-role-binding
  namespace: mypulsar
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: pulsar-operator
    namespace: {{ .Release.Namespace }}
{{- end }}
