{{- if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pulsaroperators.com.nicoloboschi
spec:
  group: com.nicoloboschi
  names:
    kind: PulsarOperator
    plural: pulsaroperators
    singular: pulsaroperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
